### ISSUE TITLE
Didn't work for me

### ISSUE THREAD

**Issue by mss-deepak** [CopeX/PNGUploadFix#1]
I am facing the issue of black backgroung for png images on my store. i use your extension but didn't fix the issue.

**Comment by pointia** [comment]
What version of Magento do you use? 1.9.3.3? In 1.9.3.4 the issue is fixed and the extension is obsolete.

Besides that you need to re upload the picture.

**Comment by mss-deepak** [comment]
I am using 1.9.3.1 magento version

**Comment by pointia** [comment]
Ok this fix is not intended to work with your version. I assume you don't have the right gd libraries installed.
